name: Flask CI and CD

on:
  push:
    branches: [ "master", "main" ]

jobs:
  # JOB 1: CI (The "Test" Phase)
  test-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install flask pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: pytest test_app.py

  # JOB 2: CD (The "Deploy" Phase)
  deploy-docker:
    needs: test-logic  # This makes sure we only deploy if tests PASS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nidhi1011/march-1:latest